<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

var menus = [

	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"管理员管理",
	                    "menuJump":"列表",
	                    "tableName":"users"
	                }
	            ],
	            "menu":"管理员信息"
	        }
	       ,{
	           "child":[
	               {
	                   "buttons":[
	                       "查看",
	                       "新增",
	                       "修改",
	                       "删除"
	                   ],
	                   "menu":"网站管理员管理",
	                   "menuJump":"列表",
	                   "tableName":"wangzhan"
	               }
	           ],
	           "menu":"网站管理员管理"
	       }
	       ,{
	           "child":[
	               {
	                   "buttons":[
	                       "查看",
	                       "新增",
	                       "修改",
	                       "删除"
	                   ],
	                   "menu":"用户管理",
	                   "menuJump":"列表",
	                   "tableName":"yonghu"
	               }
	           ],
	           "menu":"用户管理"
	       }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"餐饮信息管理",
	                    "menuJump":"列表",
	                    "tableName":"chanyinxinxi"
	                }
	            ],
	            "menu":"餐饮信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"二手物品管理",
	                    "menuJump":"列表",
	                    "tableName":"ershouwupin"
	                }
	            ],
	            "menu":"二手物品管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"失物招领管理",
			            "menuJump":"列表",
			            "tableName":"shiwuzhaoling"
			        }
			    ],
			    "menu":"失物招领管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"校车查询管理",
			            "menuJump":"列表",
			            "tableName":"xiaochechaxun"
			        }
			    ],
			    "menu":"校车查询管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"教师办公电话管理",
			            "menuJump":"列表",
			            "tableName":"bangongdianhua"
			        }
			    ],
			    "menu":"教师办公电话管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"教师部门管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryBangongdianhua"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"物品类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryErshouwupin"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"新闻类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryNews"
			        }
			
			    ],
			    "menu":"基础数据管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"轮播图管理",
			            "menuJump":"列表",
			            "tableName":"config"
			        }
			    ],
			    "menu":"轮播图管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"新闻管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"新闻管理"
	        }
	       
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"管理员",
	    "tableName":"users"
	}
	,{
        "backMenu":[
           {
               "child":[
                   {
                       "buttons":[
                           "查看",
                           "新增",
                           "修改",
                           "删除"
                       ],
                       "menu":"用户管理",
                       "menuJump":"列表",
                       "tableName":"yonghu"
                   }
               ],
               "menu":"用户管理"
           }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"餐饮信息管理",
                        "menuJump":"列表",
                        "tableName":"chanyinxinxi"
                    }
                ],
                "menu":"餐饮信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"二手物品管理",
                        "menuJump":"列表",
                        "tableName":"ershouwupin"
                    }
                ],
                "menu":"二手物品管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"失物招领管理",
			            "menuJump":"列表",
			            "tableName":"shiwuzhaoling"
			        }
			    ],
			    "menu":"失物招领管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"校车查询管理",
			            "menuJump":"列表",
			            "tableName":"xiaochechaxun"
			        }
			    ],
			    "menu":"校车查询管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"教师办公电话管理",
			            "menuJump":"列表",
			            "tableName":"bangongdianhua"
			        }
			    ],
			    "menu":"教师办公电话管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"教师部门管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryBangongdianhua"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"物品类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryErshouwupin"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"新闻类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryNews"
			        }
			
			    ],
			    "menu":"基础数据管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"轮播图管理",
			            "menuJump":"列表",
			            "tableName":"config"
			        }
			    ],
			    "menu":"轮播图管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"新闻管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"新闻管理"
            }
           
        ],
        "frontMenu":[

        ],
        "roleName":"网站管理员",
        "tableName":"wangzhan"
    }
	,
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"餐饮信息管理",
	                    "menuJump":"列表",
	                    "tableName":"chanyinxinxi"
	                }
	            ],
	            "menu":"餐饮信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"二手物品管理",
	                    "menuJump":"列表",
	                    "tableName":"ershouwupin"
	                }
	            ],
	            "menu":"二手物品管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"失物招领管理",
			            "menuJump":"列表",
			            "tableName":"shiwuzhaoling"
			        }
			    ],
			    "menu":"失物招领管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"校车查询管理",
			            "menuJump":"列表",
			            "tableName":"xiaochechaxun"
			        }
			    ],
			    "menu":"校车查询管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"教师办公电话管理",
			            "menuJump":"列表",
			            "tableName":"bangongdianhua"
			        }
			    ],
			    "menu":"教师办公电话管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"新闻管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"新闻管理"
	        }
	       
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"用户",
	    "tableName":"yonghu"
	}
];

var hasMessage = '';
